# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 09:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageStoryAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(upload_to='illustrations')),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=126)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('address_place', models.CharField(blank=True, max_length=126)),
                ('birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=126)),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, 'female'), (2, 'male'), (3, 'other')], null=True)),
                ('nationality', models.CharField(blank=True, max_length=126)),
                ('family_composition', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=126)),
                ('religious_background', models.CharField(blank=True, max_length=126)),
                ('portrait', models.ImageField(upload_to='portraits')),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.EducationLevel')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.MaritalStatus')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=254)),
                ('year', models.DurationField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.today)),
                ('introduction', models.TextField(blank=True)),
                ('subject', models.URLField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=254)),
                ('content', models.TextField(blank=True)),
                ('last_checked_on', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='StoryEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edits', to='api.Person')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='api.Story')),
            ],
        ),
        migrations.CreateModel(
            name='UrlStoryAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.URLField(max_length=254)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_attachments', to='api.Story')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='editors',
            field=models.ManyToManyField(related_name='edited_stories', through='api.StoryEdit', to='api.Person'),
        ),
        migrations.AddField(
            model_name='story',
            name='last_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Person'),
        ),
        migrations.AddField(
            model_name='parentoccupation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_occupations', to='api.Person'),
        ),
        migrations.AddField(
            model_name='imagestoryattachment',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_attachments', to='api.Story'),
        ),
    ]
