# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 14:31
from __future__ import unicode_literals
from datetime import timedelta

from django.db import migrations, models


def seconds_as_year(apps, schema_editor):
    """ Forward data migration for the Story.year field. """
    Story = apps.get_model('api', 'Story')
    for story in Story.objects.all():
        story.year = story.old_year.total_seconds()
        story.save()


def year_as_seconds(apps, schema_editor):
    Story = apps.get_model('api', 'Story')
    for story in Story.objects.all():
        story.old_year = timedelta(seconds=story.year)
        story.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161014_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='year',
            new_name='old_year',
        ),
        migrations.AddField(
            model_name='story',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=seconds_as_year,
            reverse_code=year_as_seconds,
        ),
        migrations.RemoveField(model_name='story', name='old_year'),
        migrations.AddField(
            model_name='story',
            name='year_end',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
