# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161014_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
