# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161014_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyedit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
