# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-18 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161014_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='portraits'),
        ),
    ]
