# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 11:35
from __future__ import unicode_literals

from django.db import migrations


def set_default_name(apps, schema_editor):
    """ Forward data migration for the Person.name field. """
    Person = apps.get_model('api', 'Person')
    for person in Person.objects.all():
        if not person.name:
            person.name = person.user.username
            person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161018_0956'),
    ]

    operations = [
        migrations.RunPython(code=set_default_name),
    ]
