# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-02 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20161102_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
