# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 14:04
from __future__ import unicode_literals
from datetime import date

from django.db import migrations


def convert_year_to_date(apps, schema_editor):
    """ Forward data migration for removing the Person.birth_year field. """
    Person = apps.get_model('api', 'Person')
    for person in Person.objects.all():
        if person.birth_year and not person.birth_date:
            person.birth_date = date(year=person.birth_year, month=1, day=1)
            person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_story_published'),
    ]

    operations = [
        migrations.RunPython(code=convert_year_to_date),
        migrations.RemoveField(
            model_name='person',
            name='birth_year',
        ),
    ]
